### ISSUE TITLE
Level 9 shows undefined and throws error

### ISSUE THREAD

**Issue by rubenvar** [dbrad/js13k2022#1]
Hey @dbrad, I've been trying your game today and after completing 8 levels, the 9th appears as `undefined` in the levels list:

![list](https://user-images.githubusercontent.com/35899750/191288046-50eeaac8-aa7b-4934-8164-bf2ae143f564.png)

When I move the selector to that one, the game breaks showing a black screen and the following error appears in the console:

![error](https://user-images.githubusercontent.com/35899750/191288215-02ad5ea4-3430-41f5-adb4-f402a875d3d9.png)

Hope it helps, it is a great game and a good idea, good luck in this year's competition!

**Comment by dbrad** [comment]
Thanks for the bug report! 
The Abyss was supposed to be the final challenge level, I must've forgot to cap the increment on the game level progression after beating it.
I'll be sure to fix that for the version I host over at https://js13k2022.davidbrad.ca/

**Comment by dbrad** [comment]
Note to self, cap the level list on https://github.com/dbrad/js13k2022/blob/main/src/ts/scenes/02-level-select.ts


on https://github.com/dbrad/js13k2022/blob/main/src/ts/scenes/02-level-select.ts#L31
```math.min(8, game_state[GAMESTATE_PLAYER][PLAYER_GAME_PROGRESS])```
should be 
```math.min(7, game_state[GAMESTATE_PLAYER][PLAYER_GAME_PROGRESS])```

**Comment by dbrad** [comment]
Fixed in version 1.0.1
