### ISSUE TITLE
missing license file

### ISSUE THREAD

**Issue by adbenitez** [dbrad/js13k2022#2]
hi, nice fun game! is this free/open software?  what is the license? I am interested in porting this game to [WebXDC](https://webxdc.org)

so any license that allow modifications even if restricting commercial usage would be fine

**Comment by dbrad** [comment]
Hi, the license has been updated to [CC-BY-NC-SA-4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
As noted in the link permission are as follows:
### You are free to:

- Share — copy and redistribute the material in any medium or format
- Adapt — remix, transform, and build upon the material

The licensor cannot revoke these freedoms as long as you follow the license terms.

### Under the following terms:

 **Attribution** — You must give [appropriate credit](https://creativecommons.org/licenses/by-nc-sa/4.0/#), provide a link to the license, and [indicate if changes were made](https://creativecommons.org/licenses/by-nc-sa/4.0/#). You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

**NonCommercial** — You may not use the material for [commercial purposes](https://creativecommons.org/licenses/by-nc-sa/4.0/#).

 **ShareAlike** — If you remix, transform, or build upon the material, you must distribute your contributions under the [same license](https://creativecommons.org/licenses/by-nc-sa/4.0/#) as the original.

**No additional restrictions** — You may not apply legal terms or [technological measures](https://creativecommons.org/licenses/by-nc-sa/4.0/#) that legally restrict others from doing anything the license permits.

**Comment by adbenitez** [comment]
thanks a lot for the quick reply! <3 
have a nice day!
